language: objective-c
osx_image: xcode8
script:
  - set -o pipefail
  - xcodebuild test -scheme Reactor-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c

notifications:
  slack: mailonline:CvgBKsRkoSBcuafeSy46hUKB